task_name:
  "mmer-realworld"

work_dir:
  "/media/zilun/fanxiang4t/GRSM/ImageRAG_git"

input_image_dir:
    "/data9/shz/dataset/MME-RealWorld"

patch_saving_dir:
  "patch_save_dir"

mode:
  "baseline_detection"

model_input_image_size:
  448

use_dynamic:
  1

fast_path_T:
  50

num_chunks:
  1

chunk_idx:
  0

paraphrase_model:
    model_name:
      "Qwen2.5-32B-Instruct"
    model_path:
        "/media/zilun/wd-161/hf_download/Qwen2.5-32B-Instruct"
    generation_config:
        temperature:
            1.0
        top_p:
            0.99
        max_tokens:
            512
        timeout:
            60

kw_model:
#    model_path:
#        "/media/zilun/wd-161/hf_download/all-MiniLM-L6-v2"
#    generation_config:
#        temperature:
#            0.99
#        top_p:
#            0.95
#        max_tokens:
#            512
#        timeout:
#            60

text_expansion_model:

text_embed_model:
    model_path:
      "/data1/zilun/grsm/ImageRAG_git/checkpoint/RS5M_ViT-L-14-336.pt"

fast_vlm_model:
    model_name:
      "georsclip"
    model_path:
      "/media/zilun/wd-161/RS5M/RS5M_codebase/ckpt/RS5M_ViT-L-14-336.pt"


llmvqa_model:
  model_name:
    "internvl"
  model_path:
    "/data1/zilun/grsm/ImageRAG_git/checkpoint/InternVL2_5-8B_lora_5param_dynamic_0-1000_obb2_fit_unionpatch_merged"
  load_in_8bit:
    False
  generation_config:
      temperature:
          0.2
      top_p:

      max_tokens:
          128
      timeout:
          60
      num_beams:
          1

vector_database:
    meta_pkl_path:
        "/media/zilun/fanxiang4t/GRSM/ImageRAG_git/data/georsclip_feat_label_all_server.pkl"
    img_dir:
      "/media/zilun/mx500/ImageRAG_database/cropped_img"
    text_vector_database_dir:
      "/media/zilun/fanxiang4t/GRSM/IRAG/ImageRAG_git/codebase/vector_database/text_vector_database"
    image_vector_database_dir:
      "/media/zilun/fanxiang4t/GRSM/IRAG/ImageRAG_git/codebase/vector_database/image_vector_database"
    mm_vector_database_dir:
      "/media/zilun/fanxiang4t/GRSM/IRAG/ImageRAG_git/codebase/vector_database/mm_vector_database"

question_file_path:
    "/data1/zilun/grsm/ImageRAG_0111/codebase/inference/MME-RealWorld-RS/MME_RealWorld.json"

answers_file_path:
  "/data1/zilun/grsm/ImageRAG_0111/data/eval/answer_mme-realworld-lite-8B-detection-fit_unionpatch.jsonl"

batch_size:
  1

test_prompt:
  "Select the best answer to the above multiple-choice question based on the image. Respond with only the letter (A, B, C, D, or E) of the correct option."
#  "Select the best answer to the above multiple-choice question based on the image. Provide the thinking process and give the response in the end with the letter (A, B, C, D, or E) of the correct option."
#  "Select the best answer to the above multiple-choice question based on the image. Let’s think step by step, and give the final response with the letter (A, B, C, D, or E) of the correct option."