task_name:
  "mme-realworld"

work_dir:
  "/mnt/cfs/zilun/ImageRAG"

input_image_dir:
  "/mnt/cfs/zilun/GRSM/mmerealworld-lite/data/imgs"

patch_saving_dir:
  "patch_save_dir"

model_input_image_size:
  448

use_dynamic:
  1

fast_path_T:
  70

num_chunks:
  1

chunk_idx:
  0

mode:
  "baseline"

paraphrase_model:
    model_name:
      "Qwen2.5-32B-Instruct"
    model_path:
        "/media/zilun/wd-161/hf_download/Qwen2.5-32B-Instruct"
    generation_config:
        temperature:
            1.0
        top_p:
            0.99
        max_tokens:
            512
        timeout:
            60

kw_model:
#    model_path:
#        "/media/zilun/wd-161/hf_download/all-MiniLM-L6-v2"
#    generation_config:
#        temperature:
#            0.99
#        top_p:
#            0.95
#        max_tokens:
#            512
#        timeout:
#            60

text_expansion_model:

text_embed_model:
    model_path:
      "/media/zilun/wd-161/hf_download/all-MiniLM-L6-v2"

fast_vlm_model:
    model_name:
      "georsclip"
    model_path:
      "/media/zilun/wd-161/RS5M/RS5M_codebase/ckpt/RS5M_ViT-L-14-336.pt"


llmvqa_model:
  model_name:
    "internvl"
  model_path:
      "/mnt/cfs/zilun/model/InternVL2_5-8B"
      # "/mnt/cfs/zilun/InternVL25/internvl_chat/work_dirs/internvl_chat_v2_5/InternVL2_5-8B_lora_vqa10k_zoom2k_Robust_merged"
      # "/mnt/cfs/zilun/InternVL25/internvl_chat/work_dirs/internvl_chat_v2_5/InternVL2_5-8B_lora_vqa10k_zoom2k_merged"
      # "/mnt/cfs/zilun/InternVL25/internvl_chat/work_dirs/internvl_chat_v2_5/InternVL2_5-8B_lora_vqa400k_zoom2k_merged"
      # "/mnt/cfs/zilun/InternVL25/internvl_chat/work_dirs/internvl_chat_v2_5/InternVL2_5-8B_lora32_zoom1k_merged"
      # "/mnt/cfs/zilun/InternVL25/internvl_chat/work_dirs/internvl_chat_v2_5/InternVL2_5-8B_lora32_zoom4k_merged"
      # /mnt/cfs/zilun/InternVL25/internvl_chat/work_dirs/internvl_chat_v2_5/InternVL2_5-8B_lora32_zoom4k_repeat_merged
      # /mnt/cfs/zilun/InternVL25/internvl_chat/work_dirs/internvl_chat_v2_5/InternVL2_5-8B_lora32_vqa5k_zoom4k_merged
      # /mnt/cfs/zilun/InternVL25/internvl_chat/work_dirs/internvl_chat_v2_5/InternVL2_5-8B_lora32_vqa10k_zoom4k_merged
      # /mnt/cfs/zilun/InternVL25/internvl_chat/work_dirs/internvl_chat_v2_5/InternVL2_5-8B_lora32_vqa10k_zoom4k_2epoch_merged
      # /mnt/cfs/zilun/InternVL25/internvl_chat/work_dirs/internvl_chat_v2_5/InternVL2_5-8B_lora32_vqa10k_zoom4k_5epoch_merged


  load_in_8bit:
    True
  generation_config:
      temperature:
          0.2
      top_p:

      max_tokens:
          512
      timeout:
          60
      num_beams:
          1

vector_database:
    meta_pkl_path:
      "/media/zilun/fanxiang4t/GRSM/ImageRAG_git/data/georsclip_feat_label_all_server.pkl"
    img_dir:
      "/media/zilun/mx500/ImageRAG_database/cropped_img"
    text_vector_database_dir:
      "/media/zilun/fanxiang4t/GRSM/IRAG/ImageRAG_git/codebase/vector_database/text_vector_database"
    image_vector_database_dir:
      "/media/zilun/fanxiang4t/GRSM/IRAG/ImageRAG_git/codebase/vector_database/image_vector_database"
    mm_vector_database_dir:
      "/media/zilun/fanxiang4t/GRSM/IRAG/ImageRAG_git/codebase/vector_database/mm_vector_database"

question_file_path:
  "/mnt/cfs/zilun/ImageRAG/codebase/inference/MME-RealWorld-RS/MME-RealWorld-Lite-toi_corrected.json"

answers_file_path:
  "/mnt/cfs/zilun/ImageRAG/codebase/inference/MME-RealWorld-RS/answer-corrected_zoom4klora32-mme-lite_8B_detection-gt-baseline-cot.jsonl"

batch_size:
  1

test_prompt:
  # "Select the best answer to the above multiple-choice question based on the image. Respond with only the letter (A, B, C, D, or E) of the correct option."
 "Select the best answer to the above multiple-choice question based on the image. Provide the thinking process and give the response in the end with the letter (A, B, C, D, or E) of the correct option."
#  "Select the best answer to the above multiple-choice question based on the image. Let’s think step by step, and give the final response with the letter (A, B, C, D, or E) of the correct option."