input_uhr_image_path:
  "/media/zilun/fanxiang4t/GRSM/IRAG/image/paper_teaser.png"

patch_saving_dir:
  "patch_save_dir"

model_input_image_size:
  336

fast_path_T:
  70

paraphrase_model:
    model_path:
        "/media/zilun/wd-161/hf_download/Qwen2.5-3B-Instruct"
    generation_config:
        temperature:
            1.0
        top_p:
            0.99
        max_tokens:
            512
        timeout:
            60

kw_model:
#    model_path:
#        "/media/zilun/wd-161/hf_download/all-MiniLM-L6-v2"
#    generation_config:
#        temperature:
#            0.99
#        top_p:
#            0.95
#        max_tokens:
#            512
#        timeout:
#            60

text_expansion_model:

fast_vlm_model:
    model_path:
      "/media/zilun/wd-161/RS5M/RS5M_codebase/ckpt/RS5M_ViT-L-14-336.pt"

llmvqa_model:
  model_path:
      "/media/zilun/fanxiang4t/GRSM/IRAG/imageRAG/ckpt/ckpt_llava-onevision-qwen2-0.5b-ov"

vector_database:
    meta_pkl_path:
        "/media/zilun/mx500/ImageRAG_database/cropped_img/meta_df.pkl"
    img_dir:
      "/media/zilun/mx500/ImageRAG_database/cropped_img"
    text_vector_database_dir:
      "/media/zilun/fanxiang4t/GRSM/IRAG/imageRAG/codebase/vector_database/text_vector_database"
    image_vector_database_dir:
      "/media/zilun/fanxiang4t/GRSM/IRAG/imageRAG/codebase/vector_database/image_vector_database"
    mm_vector_database_dir:
      "/media/zilun/fanxiang4t/GRSM/IRAG/imageRAG/codebase/vector_database/mm_vector_database"

